// <auto-generated />
using BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200214044221_SeedBooksInTable")]
    partial class SeedBooksInTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStore.Models.BooksDisplayed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BooksInStore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BooksInStore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookGenre = "Comedy",
                            BooksInStore = "Bossypants"
                        },
                        new
                        {
                            Id = 2,
                            BookGenre = "Comedy",
                            BooksInStore = "Yes please"
                        },
                        new
                        {
                            Id = 3,
                            BookGenre = "Comedy",
                            BooksInStore = "Me Talk Pretty One Day"
                        },
                        new
                        {
                            Id = 4,
                            BookGenre = "Drama",
                            BooksInStore = "Hamlet"
                        },
                        new
                        {
                            Id = 5,
                            BookGenre = "Drama",
                            BooksInStore = "Visul unei nopti de vara"
                        },
                        new
                        {
                            Id = 6,
                            BookGenre = "Drama",
                            BooksInStore = "Vanatorii de zmeie"
                        },
                        new
                        {
                            Id = 7,
                            BookGenre = "Science-Fiction",
                            BooksInStore = "Razboiul Lumilor"
                        },
                        new
                        {
                            Id = 8,
                            BookGenre = "Science-Fiction",
                            BooksInStore = "Solaris"
                        },
                        new
                        {
                            Id = 9,
                            BookGenre = "Science-Fiction",
                            BooksInStore = "The Left Hand of Darkness"
                        },
                        new
                        {
                            Id = 10,
                            BookGenre = "Nature-Science",
                            BooksInStore = "Walden"
                        },
                        new
                        {
                            Id = 11,
                            BookGenre = "Nature-Science",
                            BooksInStore = "Almanahul unui tinut de nisip"
                        },
                        new
                        {
                            Id = 12,
                            BookGenre = "Nature-Science",
                            BooksInStore = "H is for Hawk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
